/**
 * API client for technical analysis endpoints.
 */

import { apiClient, handleApiError } from './client';

const TECHNICAL_ANALYSIS_BASE = '/technical-analysis';

export interface IndicatorConfig {
  name: string;
  params?: Record<string, unknown>;
}

export interface CalculateIndicatorsRequest {
  symbol: string;
  timeframe?: string;
  start_date: string;
  end_date: string;
  indicators: IndicatorConfig[];
}

export interface IndicatorValue {
  timestamp: string;
  value: number;
}

export interface IndicatorResult {
  name: string;
  params: Record<string, unknown>;
  /** Present for single-output indicators (SMA, EMA, RSI, ATR). */
  values?: IndicatorValue[];
  /** Present for multi-output indicators (MACD, Bollinger Bands, Stochastic). */
  columns?: Record<string, IndicatorValue[]>;
}

export interface CalculateIndicatorsResponse {
  symbol: string;
  timeframe: string;
  /** Keys are "{name}_{hash}" generated by the backend calculator. */
  indicators: Record<string, IndicatorResult>;
}

export interface SupportedIndicator {
  name: string;
  description: string;
  params: Record<string, unknown>;
}

export const technicalAnalysisApi = {
  /**
   * Calculate one or more technical indicators for a symbol.
   */
  async calculateIndicators(
    request: CalculateIndicatorsRequest
  ): Promise<CalculateIndicatorsResponse> {
    try {
      const response = await apiClient.post<CalculateIndicatorsResponse>(
        `${TECHNICAL_ANALYSIS_BASE}/calculate`,
        request
      );
      return response.data;
    } catch (error) {
      return handleApiError(error);
    }
  },

  /**
   * Get a list of all supported technical indicators and their parameters.
   */
  async getSupportedIndicators(): Promise<{ indicators: SupportedIndicator[] }> {
    try {
      const response = await apiClient.get<{ indicators: SupportedIndicator[] }>(
        `${TECHNICAL_ANALYSIS_BASE}/indicators`
      );
      return response.data;
    } catch (error) {
      return handleApiError(error);
    }
  },
};
