import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { beforeEach, describe, expect, it, vi } from 'vitest';

import { StrategyForm } from './StrategyForm';
import { StrategyType } from '@/lib/types/strategy';
import { compileStrategy } from '@/lib/api/strategies';

vi.mock('@/lib/api/strategies', () => ({
  compileStrategy: vi.fn(),
}));

describe('StrategyForm', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('shows a validation error and blocks submit when the JSON spec is invalid', async () => {
    const user = userEvent.setup();
    const onSubmit = vi.fn().mockResolvedValue(undefined);
    const { container } = render(<StrategyForm onSubmit={onSubmit} />);

    await user.type(screen.getByPlaceholderText('e.g., RSI Mean Reversion'), 'Mean Reversion');

    const textareas = container.querySelectorAll('textarea');
    fireEvent.change(textareas[2], { target: { value: '{invalid json' } });

    await user.click(screen.getByRole('button', { name: 'Create Strategy' }));

    expect(await screen.findByText('Invalid JSON in strategy specification')).toBeInTheDocument();
    expect(onSubmit).not.toHaveBeenCalled();
  });

  it('submits normalized form data with metadata updated from the form fields', async () => {
    const user = userEvent.setup();
    const onSubmit = vi.fn().mockResolvedValue(undefined);
    const { container } = render(<StrategyForm onSubmit={onSubmit} />);

    await user.type(screen.getByPlaceholderText('e.g., RSI Mean Reversion'), 'Trend Follower');
    await user.type(screen.getByPlaceholderText('Describe your trading strategy...'), 'Follows breakouts');

    const specTextarea = container.querySelectorAll('textarea')[2];
    fireEvent.change(specTextarea, {
      target: {
        value: JSON.stringify(
          {
            kind: 'technical',
            metadata: { name: 'Old Name', description: 'Old description', version: 1 },
            market: { timeframe: '1d', symbols: [] },
            indicators: [],
            rules: {
              entry: {
                type: 'compare',
                left: { type: 'price', field: 'close' },
                operator: '>',
                right: { type: 'constant', value: 0 },
              },
              exit: {
                type: 'compare',
                left: { type: 'price', field: 'close' },
                operator: '<',
                right: { type: 'constant', value: 0 },
              },
              filters: [],
            },
            risk: { position_sizing: { method: 'fixed_percentage', percentage: 0.1 }, long_only: true },
            execution: {},
          },
          null,
          2
        ),
      },
    });

    await user.click(screen.getByRole('button', { name: 'Create Strategy' }));

    await waitFor(() => expect(onSubmit).toHaveBeenCalledTimes(1));
    expect(onSubmit).toHaveBeenCalledWith({
      name: 'Trend Follower',
      description: 'Follows breakouts',
      strategy_type: StrategyType.TECHNICAL,
      spec: expect.objectContaining({
        metadata: expect.objectContaining({
          name: 'Trend Follower',
          description: 'Follows breakouts',
        }),
      }),
    });
  });

  it('compiles a natural-language prompt and updates the summary and form fields', async () => {
    const user = userEvent.setup();
    vi.mocked(compileStrategy).mockResolvedValue({
      normalized_spec: {
        kind: 'technical',
        metadata: {
          name: 'Compiled Strategy',
          description: 'Generated by compiler',
          version: 1,
        },
      },
      summary: 'Compiled strategy summary',
      warnings: ['Compiler warning'],
      prompt_warnings: ['Prompt warning'],
    });

    render(<StrategyForm onSubmit={vi.fn().mockResolvedValue(undefined)} />);

    await user.type(
      screen.getByPlaceholderText(
        'Buy SPY when 14-day RSI falls below 30, sell when it rises above 70, use 10% position sizing on daily bars.'
      ),
      'Generate a momentum strategy'
    );

    await user.click(screen.getByRole('button', { name: 'Compile Strategy' }));

    expect(await screen.findByText('Compiled strategy summary')).toBeInTheDocument();
    expect(screen.getByText('Prompt warning')).toBeInTheDocument();
    expect(screen.getByText('Compiler warning')).toBeInTheDocument();
    expect(screen.getByDisplayValue('Compiled Strategy')).toBeInTheDocument();
    expect(screen.getByDisplayValue('Generated by compiler')).toBeInTheDocument();

    expect(compileStrategy).toHaveBeenCalledWith({
      prompt: 'Generate a momentum strategy',
      name: undefined,
      description: undefined,
    });
  });
});
